model:
  pretrained_model: dmis-lab/biobert-base-cased-v1.1
  out_dir: biobert_qa
  max_len: 384
  batch_size: 2
  lr: 3e-5
  n_epochs: 3
lora:
  enabled: False
data:
  subset: 200 # Load a small subset first to verify
  dataset: covid_qa